### ISSUE TITLE
Making pdf reader using python.

### ISSUE THREAD

**Issue by gurleen3** [Learn-Write-Repeat/python#4]
I am a part of OpenCV scholarship program from your organization. I wanted to contribute for hacktoberfest, but couldn't find a python repo in the contributions.  If you may allow, can I contribute to the repo with how to make your computer read any pdf file?

**Comment by arpit-dwivedi** [comment]
@gurleen3 for any contributions for **hacktoberfest**, you can contribute in [this repository](https://github.com/Learn-Write-Repeat/Open-contributions), please go through [this issue](https://github.com/Learn-Write-Repeat/Open-contributions/issues/173) for the same.
